name: Patch Fonts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get -y install unzip curl git fontforge python3-fontforge fonttools python-is-python3 python3-pip
          pip3 install configparser

      - name: Patch fonts
        run: |
          chmod +x patch.sh
          ./patch.sh
          zip CaskaydiaCove.zip patched-fonts/*
          
      - name: Set variable
        run: |
          echo "version=$(curl -s https://api.github.com/repos/microsoft/cascadia-code/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_ENV
          echo "otherversion=$(curl -s https://api.github.com/repos/thatweirdandrew/caskaydia-cove/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_ENV
          echo "${{ env.version }}"
        shell: bash
        
      - name: Publish release
        uses: ncipollo/release-action@v1
        if: ${{ env.version != env.otherversion }}
        with:
          artifacts: "CaskaydiaCove.zip"
          tag: "${{ env.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: main
